name: Test, Build and Upload artifact

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    name: 990604/javaclothes
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0
      - run: mvn -f pom.xml clean compile

  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Java 8 build, deliver artifact and container
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Start MongoDB for integration test
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2

      - name: Test and build project
        run: mvn -f pom.xml clean install

      - name: Show contents of the current working directory
        run: ls -la

      - name: Show contents of the target directory
        run: ls -la target

      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v1
        with:
          name: javaclothes-artifact.jar
          path: ./target/order-0.0.1.jar

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: 990604
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t 990604/javaclothes:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push 990604/javaclothes:latest